#!/bin/bash

DIRECTORY="$(dirname "$0")"

function error {
  echo -e "\e[91m$1\e[39m"
  if [ "$runmode" == 'gui' ];then
    zenity --error --text="TwistUP error:\n$1" --no-wrap
  fi
  exit 1
}

screen_width="$(xdpyinfo | grep 'dimensions:' | tr 'x' '\n' | tr ' ' '\n' | sed -n 7p)"
screen_height="$(xdpyinfo | grep 'dimensions:' | tr 'x' '\n' | tr ' ' '\n' | sed -n 8p)"

yad --form --text='Twister OS can be updated.' \
  --on-top --skip-taskbar --undecorated --close-on-unfocus \
  --geometry=260+$((screen_width-262))+$((screen_height-150)) \
  --field="Never show again:CHK"  --image=/home/pi/TwistUP/icons/logo.png \
  --button="Details!${DIRECTORY}/icons/info.png":0 --button="Close!${DIRECTORY}/icons/exit.png!We"\'"ll remind you in a week.":1


